name: Change Tracking Marker

on:
    push: {}


jobs:

  newrelic-prod:
    runs-on: ubuntu-latest
    name: New Relic
    if: >-
        github.repository == 'breatheco-de/apiv2' &&
        github.event_name == 'push' &&
        github.ref == 'refs/heads/main'

    steps:

      # This step builds a var with the release tag value to use later
      - name: Set Release Version from Tag
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      # This step creates a new Change Tracking Marker
      - name: New Relic Application Deployment Marker
        uses: newrelic/deployment-marker-action@v2.3.0
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
          version: "${{ env.RELEASE_VERSION }}"
          user: "${{ github.actor }}"

  newrelic-dev:
    runs-on: ubuntu-latest
    name: New Relic
    if: >-
        github.repository == 'breatheco-de/apiv2' &&
        github.event_name == 'push' &&
        github.ref == 'refs/heads/development'

    steps:

        # This step builds a var with the release tag value to use later
        - name: Set Release Version from Tag
          run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

        # This step creates a new Change Tracking Marker
        - name: New Relic Application Deployment Marker
          uses: newrelic/deployment-marker-action@v2.3.0
          with:
            apiKey: ${{ secrets.NEW_RELIC_API_KEY_DEV }}
            guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID_DEV }}
            version: "${{ env.RELEASE_VERSION }}"
            user: "${{ github.actor }}"
