# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          PYTHONUNBUFFERED=1
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev --system --deploy --ignore-pipfile
      - name: Test with pytest
        run: |
          pipenv run cov_ci

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          if: ${{ github.event_name == 'pull_request' || github.repository == 'breatheco-de/apiv2' }}

      # - name: Coveralls
      #   run: |
      #     echo $GITHUB_TOKEN
      #     echo $COVERALLS_TOKEN
      #     echo $GITHUB_WORKFLOW
      #     echo ${{ secrets.COVERALLS_TOKEN }}
      #     echo ${{ secrets.COVERALLS_TOKEN }}
      #     coveralls

      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage data to coveralls.io
        run: |
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          if: ${{ github.event_name == 'pull_request' || github.repository == 'breatheco-de/apiv2' }}
