# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv

      # - name: Python cache
      #   id: cache-pipenv
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.local/share/virtualenvs
      #     key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install dependencies
        # if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          PYTHONUNBUFFERED=1
          pipenv install --dev --system --deploy --ignore-pipfile

      # - name: Install dependencies
      #   run: |
      #     PYTHONUNBUFFERED=1
      #     python -m pip install --upgrade pip
      #     python -m pip install pipenv
      #     pipenv install --dev --system --deploy --ignore-pipfile

      - name: Test with pytest
        run: |
          pipenv run pcov_ci

      - uses: codecov/codecov-action@v1
        if: ${{ github.event_name == 'pull_request' || github.repository == 'breatheco-de/apiv2' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      - name: Upload coverage data to coveralls.io
        if: ${{ github.event_name == 'pull_request' || github.repository == 'breatheco-de/apiv2' }}
        run: |
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ github.token }}
